version: '3'
services:
  documentserver:
    image: onlyoffice/documentserver
    environment:
      - JWT_ENABLED=false
#      - LETS_ENCRYPT_MAIL=tmasik.t.210@gmail.com
#      - LETS_ENCRYPT_DOMAIN=bamaec.ru
    ports:
     - 11115:80
     - 11114:443
    volumes:
     - onlyofficeetc:/etc/onlyoffice/documentserver
     - onlyofficedb:/var/lib/postgresql
  postgres:
    image: postgres
    restart: always
    ports:
     - 11111:5432
    environment:
      - POSTGRES_PASSWORD=thepassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgresdb:/var/lib/postgresql/data
  app:
    image: sconf
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
     - 3000:3000
  pgadmin:
    image: dpage/pgadmin4
    ports:
     - 11113:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=stepin@hig.com
      - PGADMIN_DEFAULT_PASSWORD=stepin
    volumes:
     - ./servers.json:/pgadmin4/servers.json
  fileuploader:
    image: tmasikt/sconf-file-uploader
    ports:
     - 8080:8080
    volumes:
     - presentations:/app/presentations


networks:
  default:
    driver: bridge

volumes:
  postgresdb:
  onlyofficeetc:
  onlyofficecache:
  onlyofficedb:
  presentations:
  onlyofficedata:
